model_user:
  password_minimum: 6
  name_maximum: 50
  email_maximum: 255
user_helper:
  size: 80
seed:
  correct_answer: "-C"
middleware:
  path_info: "PATH_INFO"
  path: "/search_suggestions"
  respone_code: 200
  content_type: "Content-Type"
  type: "application/json"
  params: "term"
task:
  searches_desc: "Generate search suggesstions from Questions"
admin_users_controller:
  per_page: 5
categories_controller:
  per_page: 9
admin_categories_controller:
  per_page: 5
lessons_controller:
  get: 5
  per_page: 5
lesson_view:
  minute: "00"
  second: "20"
  answer_count: 0
user_controller:
  per_page: 5
